import Head from "next/head";
import Image from "next/image";
import { Footer, Navbar } from "../components";
import HomeScreen from "./HomeScreen";
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HomeScreen />
    </div>
  );
}
